import localFont from "next/font/local";
import { Container, Grid2 } from "@mui/material";
import List from '@mui/material/List';
import PlaceIcon from '@mui/icons-material/Place';
import ListItemComponent from "./components/listItemComponent";
import "./globals.css";
import NavigationBar from "./components/appbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const locations = [
  "Kinshasa", "Bas-Uele", "Equateur", "Haut-Katanga", "Haut-Lomami",
  "Haut-Uele", "Ituri", "Kasaï", "Kasaï-Central", "Kasaï-Oriental",
  "Kongo-Central", "Kwango", "Kwilu", "Lomami", "Lualaba",
  "Mai-Ndombe", "Maniema", "Mongala", "Nord-Kivu", "Nord-Ubangi",
  "Sankuru", "Sud-Kivu", "Sud-Ubangi", "Tanganyika", "Tshopo", "Tshuapa"
];

export default function RootLayout({ children }) {
  return (<>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavigationBar />
        <Container>
          <Grid2 container spacing={2}>
            <Grid2
              size={{ md: 3 }}
              sx={{
                display: { xs: 'none', md: 'block' },
                backgroundColor: "white",
                maxHeight: "100vh", // Set a maximum height for the scrollable area
                overflowY: "auto" // Enable vertical scrolling
              }}>
              <List>
                {locations.map((location) => (
                  <ListItemComponent key={location} icon={PlaceIcon} primaryText={location} />
                ))}
              </List>
            </Grid2>
            <Grid2 size={{ md: 9, xs: 12 }}>
              {children}
            </Grid2>
          </Grid2>
        </Container>
      </body>
    </html>
  </>
  );
}
