import { Card, Container, Grid2 } from "@mui/material";
import WebsiteLayout from "./layout/websiteLayout";
import List from '@mui/material/List';
import PlaceIcon from '@mui/icons-material/Place';
import ListItemComponent from "./components/listItemComponent";
import InteractiveMap from "./components/mapsComponet";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <WebsiteLayout>
      <Container>
        <Grid2 container spacing={2}>
          <Grid2
            size={{ md: 3 }}
            sx={{
              display: { xs: 'none', md: 'block' },
              backgroundColor: "white",
              maxHeight: "100vh", // Set a maximum height for the scrollable area
              overflowY: "auto" // Enable vertical scrolling
            }}>
            <List>
              <ListItemComponent icon={PlaceIcon} primaryText="Kinshasa" />
              <ListItemComponent icon={PlaceIcon} primaryText="Bas-Uele" />
              <ListItemComponent icon={PlaceIcon} primaryText="Equateur" />
              <ListItemComponent icon={PlaceIcon} primaryText="Haut-Katanga" />
              <ListItemComponent icon={PlaceIcon} primaryText="Haut-Lomami" />
              <ListItemComponent icon={PlaceIcon} primaryText="Haut-Uele" />
              <ListItemComponent icon={PlaceIcon} primaryText="Ituri" />
              <ListItemComponent icon={PlaceIcon} primaryText="Kasaï" />
              <ListItemComponent icon={PlaceIcon} primaryText="Kasaï-Central" />
              <ListItemComponent icon={PlaceIcon} primaryText="Kasaï-Oriental" />
              <ListItemComponent icon={PlaceIcon} primaryText="Kongo-Central" />
              <ListItemComponent icon={PlaceIcon} primaryText="Kwango" />
              <ListItemComponent icon={PlaceIcon} primaryText="Kwilu" />
              <ListItemComponent icon={PlaceIcon} primaryText="Lomami" />
              <ListItemComponent icon={PlaceIcon} primaryText="Lualaba" />
              <ListItemComponent icon={PlaceIcon} primaryText="Mai-Ndombe" />
              <ListItemComponent icon={PlaceIcon} primaryText="Maniema" />
              <ListItemComponent icon={PlaceIcon} primaryText="Mongala" />
              <ListItemComponent icon={PlaceIcon} primaryText="Nord-Kivu" />
              <ListItemComponent icon={PlaceIcon} primaryText="Nord-Ubangi" />
              <ListItemComponent icon={PlaceIcon} primaryText="Sankuru" />
              <ListItemComponent icon={PlaceIcon} primaryText="Sud-Kivu" />
              <ListItemComponent icon={PlaceIcon} primaryText="Sud-Ubangi" />
              <ListItemComponent icon={PlaceIcon} primaryText="Tanganyika" />
              <ListItemComponent icon={PlaceIcon} primaryText="Tshopo" />
              <ListItemComponent icon={PlaceIcon} primaryText="Tshuapa" />
            </List>
          </Grid2>
          <Grid2 size={{ md: 9, xs: 12 }}>
            <Card sx={{ maxWidth: "100%", maxHeight: "200px" }}>
            </Card>
            <Grid2 >
              <InteractiveMap />
            </Grid2>
          </Grid2>
        </Grid2>
      </Container>
    </WebsiteLayout>
  );
}
